### PR TITLE
re-factor analog button functions to support multiple button lines.

### PR DESCRIPTION
**Pull request by w6ipa**
The processing of analog button has been moved out of the main ino - into an internal library.
the main path works - but memory repeat did not work and need to be checked a bit more.
Also - special cases like reversed buttons and dfrobot lcd have not been tested.

### CODE REVIEW

**Comment by VK2EFL** [comment]
Any chance that the extra functions that can be done by a button, such as Tx select, memory repeat (press memory button and tap a paddle) and program a memory from Command Mode by pressing a button, can be emulated with the keypad?
I guess this is more of a question for the keypad section of the code.
I have been able to modify the keypad section of the code to do the transmitter switching, but could not get the code to recognise the simultaneous press of a keypad button and a paddle, or a keypad press when in Command Mode.
77 Fred VK2EFL

**Comment by k3ng** [comment]
Sorry it took me so long, but I merged this.  For some reason it created a src directory in the root and in dir k3ng_keyer.  You know why?  Can I delete the src dir in the root?

**Comment by VK2EFL** [comment]
Anthony,
I am certainly no expert on git or github.
After looking at the tutorial I was amazed that I got my previous pull request submitted properly.
It has been a while, and I would need to re-read the git documentation to do it again.

I actually have done a little bit of coding around a trivial vanity feature where the user can specify a custom line of text to display on startup. This would only happen if there was a display an DO_NOT_SAY-HI is defined for a 2 line display (the custom text line would be displayed on that second line) or if the implementation had a four line display and the custom line would show on the fourth line.
Many hams like to have their callsign and name appear as the unit starts up.
73 Fred VK2WS (callsign has changed)
________________________________

**Comment by k3ng** [comment]
Hi Fred.  I would welcome that feature.  Please submit in a pull request if you can.  73 Goody

**Pull request merged**
