### PR TITLE
Support for Adafruit i2c/SPI LCD Backpack

### PR DESCRIPTION
**Pull request by flickerfly**
The Adafruit i2c/SPI LCD Character backpack is very similar to the AdaFruit RGB LCD Shield, but more compact and flexible regarding the displays that can be used with it. The i2c LCD backpack uses an MCP23008 to control whatever standard 8x1 to 20x4 LCD display you throw at it. 

Most of this request is adding the Adafruit library needed to the libraries directory. That is completed in the second commit. The first commit has the actual code changes to the sketch which very closely emulates the RGB LCD Shield code.

Product Details: https://www.adafruit.com/product/292

### CODE REVIEW

**Comment by flickerfly** [comment]
I saw you asked for a callsign for another submission somewhere so I'll drop that here:
Josiah Ritchie KE0BLL

**Comment by k3ng** [comment]
Hi Josiah.  I just wanted to let you know I received your communications,
I've just been tied up the past few nights.  I hope to get caught up and
respond tonight.  Thanks and 73!

**Comment by flickerfly** [comment]
No problem. I get that life takes priority over hobbies. I didn't mean to be pushy, just trying to reduce comms needed for completion. Thanks for the note and thanks for this great project. I'm enjoying it a great deal.

**Comment by k3ng** [comment]
Merged!  Thanks!

**Pull request merged**
