### PR TITLE
Adding support for the adafruit i2c/SPI character LCD backpack

### PR DESCRIPTION
**Pull request by flickerfly**
This is very similar to the AdaFruit RGB LCD Shield, but a
slightly different chip on the backpack allows the use of any
standard LCD display between 8x1 to 20x4.

This backpack uses the MCP23008 chip.
Product: https://www.adafruit.com/product/292

### CODE REVIEW

**Comment by flickerfly** [comment]
Just realized I forget the dependency. This requires the following AdaFruit library to operate: https://github.com/adafruit/LiquidCrystal/archive/master.zip

**Comment by flickerfly** [comment]
Sorry, this seems to have added my other commits after I created the initial pull. I'm going to close this and try again with only the relevant materials. I do apologize for my newbness.

**Comment by k3ng** [comment]
No worries.  I'm not completely familiar with pull requests; I'm a noob as well :-)

**Comment by flickerfly** [comment]
Ha, thanks. If it is useful, I found creating a branch just for this purpose was the needed solution.

**Pull request closed without merging**
